thisdir = class/System.CompilerServices.InteropServices
SUBDIRS = 
include ../../build/rules.make

RESOURCE_FILES =

LIBRARY = System.Private.CompilerServices.ICastable.dll
LIB_REFS = 
LIB_MCS_FLAGS =

NO_TEST = yes

include ../../build/library.make
